[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.5"

[prune]
  go-tests = true
  unused-packages = true
